<?php

namespace Proxies\__CG__\AddressBookBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Person extends \AddressBookBundle\Entity\Person implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'AddressBookBundle\\Entity\\Person' . "\0" . 'squads', '' . "\0" . 'AddressBookBundle\\Entity\\Person' . "\0" . 'emails', '' . "\0" . 'AddressBookBundle\\Entity\\Person' . "\0" . 'addresses', '' . "\0" . 'AddressBookBundle\\Entity\\Person' . "\0" . 'phones', '' . "\0" . 'AddressBookBundle\\Entity\\Person' . "\0" . 'id', '' . "\0" . 'AddressBookBundle\\Entity\\Person' . "\0" . 'name', '' . "\0" . 'AddressBookBundle\\Entity\\Person' . "\0" . 'surname', '' . "\0" . 'AddressBookBundle\\Entity\\Person' . "\0" . 'description', '' . "\0" . 'AddressBookBundle\\Entity\\Person' . "\0" . 'photo');
        }

        return array('__isInitialized__', '' . "\0" . 'AddressBookBundle\\Entity\\Person' . "\0" . 'squads', '' . "\0" . 'AddressBookBundle\\Entity\\Person' . "\0" . 'emails', '' . "\0" . 'AddressBookBundle\\Entity\\Person' . "\0" . 'addresses', '' . "\0" . 'AddressBookBundle\\Entity\\Person' . "\0" . 'phones', '' . "\0" . 'AddressBookBundle\\Entity\\Person' . "\0" . 'id', '' . "\0" . 'AddressBookBundle\\Entity\\Person' . "\0" . 'name', '' . "\0" . 'AddressBookBundle\\Entity\\Person' . "\0" . 'surname', '' . "\0" . 'AddressBookBundle\\Entity\\Person' . "\0" . 'description', '' . "\0" . 'AddressBookBundle\\Entity\\Person' . "\0" . 'photo');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Person $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', array($name));

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', array());

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setSurname($surname)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSurname', array($surname));

        return parent::setSurname($surname);
    }

    /**
     * {@inheritDoc}
     */
    public function getSurname()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSurname', array());

        return parent::getSurname();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', array($description));

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', array());

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setPhoto($photo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhoto', array($photo));

        return parent::setPhoto($photo);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhoto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhoto', array());

        return parent::getPhoto();
    }

    /**
     * {@inheritDoc}
     */
    public function addSquads(\AddressBookBundle\Entity\Squad $squads)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addSquads', array($squads));

        return parent::addSquads($squads);
    }

    /**
     * {@inheritDoc}
     */
    public function removeSquads(\AddressBookBundle\Entity\Squad $squads)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeSquads', array($squads));

        return parent::removeSquads($squads);
    }

    /**
     * {@inheritDoc}
     */
    public function getSquads()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSquads', array());

        return parent::getSquads();
    }

    /**
     * {@inheritDoc}
     */
    public function addEmail(\AddressBookBundle\Entity\Email $emails)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addEmail', array($emails));

        return parent::addEmail($emails);
    }

    /**
     * {@inheritDoc}
     */
    public function removeEmail(\AddressBookBundle\Entity\Email $emails)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeEmail', array($emails));

        return parent::removeEmail($emails);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmails()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmails', array());

        return parent::getEmails();
    }

    /**
     * {@inheritDoc}
     */
    public function addAddress(\AddressBookBundle\Entity\Address $addresses)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAddress', array($addresses));

        return parent::addAddress($addresses);
    }

    /**
     * {@inheritDoc}
     */
    public function removeAddress(\AddressBookBundle\Entity\Address $addresses)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeAddress', array($addresses));

        return parent::removeAddress($addresses);
    }

    /**
     * {@inheritDoc}
     */
    public function getAddresses()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAddresses', array());

        return parent::getAddresses();
    }

    /**
     * {@inheritDoc}
     */
    public function addPhone(\AddressBookBundle\Entity\Phone $phones)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPhone', array($phones));

        return parent::addPhone($phones);
    }

    /**
     * {@inheritDoc}
     */
    public function removePhone(\AddressBookBundle\Entity\Phone $phones)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePhone', array($phones));

        return parent::removePhone($phones);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhones()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhones', array());

        return parent::getPhones();
    }

}
